### PR TITLE
Help required.

### PR DESCRIPTION
**Pull request by MartinCernohorsky**
Hey,

some changes have been made for sure, but I don't think I remember them all. Most important thing : it does not work. Some notes below.

1. Some ID fields in DB uses INT some uses Guids. Which one is correct?
2. I forced UQ constraint to ProductType.Type attribute since it is a good thing to have I think.
3. Campaign.Discount is set to double. Was a string before.

4. There are new DTOs. Some are not implemented.
5. New enum for productTypes. I also use it in code. It is kind a awkward but it works. I do not know how later sync is processed (having same types in code and in DB).
6. Inicialization of nested referential types. Is there a rule of thumb how to do it? Because of relations it could get into endless loops, otherwise not everything is returned. While one could consider some parameters more important then the others I would like the know which are those to return always. 
7. ProductService.AddProduct . Would be so kind and try to find why it always try to store new product type into a database? Used solution is not the first I have tired, but even it gets existing productType from DB it try to store it again....

I think it is too late to split commits into some logical sets like new DTOs, new services , etc. so here it is all in one package. I'll try to do it correctly latter.

### CODE REVIEW

**Comment by mozdren** [comment]
Ad 1) use Guids
Ad 2) ok
Ad 3) Discount should be Double
Ad 4) that is normal, will be implemented later
Ad 5-7) will discuss later

**Comment by mozdren** [comment]
Should this be resolved, or is it obsolete?

**Comment by MartinCernohorsky** [comment]
I think it is not necessary anymore. I just would like to ask if there is a EF class let's say product with 

private ProductType ProductType {get;set;}
private Guid ProductTypeId{get;set;};

is this correct or it is a residue of EF mapping and there should be only one of them. I really do not see any advantages of this. Are there any ? Thank you.

**Comment by mozdren** [comment]
I am not sure what is correct. Try to do annotation of the code (right click on the code and press annotate) and see who was the last one to change it. Then ask him, please. I just do not remember now what was the last decision. :(

**Comment by MartinCernohorsky** [comment]
Ok, thank you. Due to fact that parts of this request has been uploaded from diffrent commits it is ok to close.

**Pull request closed without merging**
